apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /argocd-applicationset-controller
  labels:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: applicationset-controller
  name: argocd-applicationset-controller
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|argocd-applicationset-controller'
