apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
spec:
  source:
    kustomize:
      version: custom
