apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - name: install-kustomize-5-1-1
          image: alpine:3.11.3
          command: ["/bin/sh", "-c"]
          args:
            - set -e;
              set -x;
              wget -O /custom-tools/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.1.1/kustomize_v5.1.1_linux_amd64.tar.gz;
              tar -xf /custom-tools/kustomize.tar.gz -C /custom-tools/;
              mv /custom-tools/kustomize /custom-tools/kustomize_5_1_1;
              chmod +x /custom-tools/kustomize_5_1_1;
              wget -O /custom-tools/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz;
              tar -xf /custom-tools/kustomize.tar.gz -C /custom-tools/;
              mv /custom-tools/kustomize /custom-tools/kustomize_4_2_0;
              chmod +x /custom-tools/kustomize_4_2_0;
              rm /custom-tools/kustomize.tar.gz;
              set +x;
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools