apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - name: install-kustomize-custom
          image: alpine:3.11.3
          command: ["/bin/sh", "-c"]
          args:
            - set -e;
              set -x;
              wget -O /custom-tools/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${VERSION}/kustomize_v${VERSION}_${PLATFORM}_${ARCH}.tar.gz;
              tar -xf /custom-tools/kustomize.tar.gz -C /custom-tools/;
              rm /custom-tools/kustomize.tar.gz;
              mv /custom-tools/kustomize /custom-tools/kustomize_custom;
              set +x;
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
          env:
            - name: VERSION
              value: 4.2.0
            - name: PLATFORM
              value: linux
            - name: ARCH
              value: amd64
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools