apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /argocd-application-controller
  labels:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: application-controller
  name: argocd-application-controller
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|argocd-application-controller'
