apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

vars:
- name: ENVIRONMENT
  objref:
    kind: Namespace
    name: argocd
    apiVersion: v1
  fieldref:
    fieldpath: metadata.labels.environment
