apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /argocd-cm
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|argocd-cm'
