apiVersion: v1
kind: Secret
metadata: # kpt-merge: /argocd-secret
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|default|argocd-secret'
type: Opaque
