apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: /argocd-application-controller
  name: argocd-application-controller
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|StatefulSet|default|argocd-application-controller'
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        args:
        - /usr/local/bin/argocd-application-controller
        env:
        - name: ARGOCD_REDIS
          valueFrom:
            configMapKeyRef:
              name: argocd-cmd-params-cm
              key: redis.server
