apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /argocd-notifications-controller
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-controller
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|argocd-notifications-controller'
